# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    access_denied_url: /
    encoders:
        UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 13

    role_hierarchy:
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_MODERATOR]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database:
            entity:
                class: UserBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout_on_user_change: true
            provider: database
            logout:
                path: user_logout
            form_login:
                login_path: user_login
                check_path: user_login
